### ISSUE TITLE
Reading the edgelist using CSRGraphs.

### ISSUE THREAD

**Issue by timilsinamohan** [VHRanger/nodevectors#13]
Thanks for this great work. 

I have a big graph of size 10 GB I use CSRGraphs to load the edgelist and compute the node embedding using node2vec.  But, I got this problem while reading a graph. Here is the error I encountered for what I mean.

```
import csrgraph as cg
G = cg.read_edgelist("karate.txt",sep = "\t")
TypeError: sort_values() got an unexpected keyword argument 'ignore_index'
```
Any suggestion to fix this.
Thanks in advance.

**Comment by VHRanger** [comment]
This is related to you pandas version, which is outdated. The `ignore_index` parameter has been introduced in version 1.0

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html

I'll try to release a version of CSRGraphs which supports older pandas versions.

Please raise an issue here or in the CSRGraphs package if you run into other issues reading large graphs -- This is the first release so there may still be problems related to reading edge lists directly into CSRGraphs for some types of graphs.
