### ISSUE TITLE
Node2Vec IndexError: list index out of range

### ISSUE THREAD

**Issue by janvekarnaveed** [VHRanger/nodevectors#19]
Hi,

After the fix of https://github.com/VHRanger/CSRGraph/issues/3. I was successfully able to load my dataset in CSRGraph. But when I ran the following command, I get an error -
`from nodevectors import Node2Vec`
`g2v = Node2Vec()`
`g2v.fit(G)`

Error - ---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-61-cdea93ea4628> in <module>
      3     # way faster than other node2vec implementations
      4     # Graph edge weights are handled automatically
----> 5 g2v.fit(G)

~/SageMaker/CSRGraph/nodevectors/nodevectors/node2vec.py in fit(self, nxGraph)
     93         node_names = list(nxGraph)
     94         G = cg.csrgraph(nxGraph, threads=self.threads)
---> 95         if type(node_names[0]) not in [int, str, np.int32, np.uint32, 
     96                                        np.int64, np.uint64]:
     97             raise ValueError("Graph node names must be int or str!")

IndexError: list index out of range

Ids in my datafile are int64 datatype. Interestingly when I run the following command. I can execute successfully.
`from nodevectors import GGVec`
`ggvec_model = GGVec()`
`embeddings = ggvec_model.fit_transform(G)`

**Comment by VHRanger** [comment]
OK, thanks a lot for filing the issue, I'll look into it later today.

I need to make all the code here differentiate between graph node ID and node name. 

The code used to assume ID and name were the same, which is why we had all these constraints on what you could put in an edgelist file.

I'll have it fixed here and add some tests to make sure the interaction between the two packages is good.

**Comment by VHRanger** [comment]
Try the latest release. It should be fixed and tested.

Just update nodevectors on pip (which should upgrade csrgraphs to 0.1.20 as well).

If you run into more problems please file more issues! There might be some intermittent segfault bug which I may have to chase down now.

Thanks for the feedback.
