### ISSUE TITLE
Node2Vec Segmentation Fault

### ISSUE THREAD

**Issue by janvekarnaveed** [VHRanger/nodevectors#20]
Hi,

Thanks for solving previous issue https://github.com/VHRanger/nodevectors/issues/19. However, now I am receiving segmentation fault error on running
from nodevectors import Node2Vec
g2v = Node2Vec()
g2v.fit(G)

Additionally, when I pip3 install CSRGraph and nodevectors, installation completes, but when I import them, I get No module found error.

**Comment by janvekarnaveed** [comment]
just checking if there was any update for the seg fault issue

**Comment by VHRanger** [comment]
Should be fixed now with the new release on CSRGraphs
