### ISSUE TITLE
I run the given short example... (partial success)

### ISSUE THREAD

**Issue by Hyrundo** [VHRanger/nodevectors#22]
Hello Mr. Matt Ranger, 

I installed the _nodevectors_ package on my Mac OS Sierra, I verified to have all the required Python packages available with 'pip list' and then tried to run the given short example as a filename.py file. Here the CL trace:

 % python networkx-test.py 
Making walks... Done, T=2.94
Mapping Walk Names... Done, T=0.08
Training W2V... Done, T=0.85
Traceback (most recent call last):
  File "networkx-test.py", line 19, in <module>
    g2v = Node2vec.load('node2vec.pckl')     # it gets blocked at this point.
NameError: name 'Node2vec' is not defined  

...any hint/feedback/re-testing would be appreciated. 
Thank you, BR

H.

**Comment by VHRanger** [comment]
WHen you say example you mean the one in the README?

```python
    import networkx as nx
    from nodevectors import Node2Vec

    # Test Graph
    G = nx.generators.classic.wheel_graph(100)
 
    # Fit embedding model to graph
    g2v = Node2Vec()
    # way faster than other node2vec implementations
    # Graph edge weights are handled automatically
    g2v.fit(G)
 
    # query embeddings for node 42
    g2v.predict(42)
```

Note first that you have no `from nodevectors import Node2Vec` in the code you linked. Also note the capital V in the `Node2Vec` class name whereas what you have is `Node2vec`

It seems that this is a typo in the example, which I fixed. Try to run it with the correct name

**Comment by Hyrundo** [comment]
Hello Mr. Matt Ranger,

thank you for your kind reply! What I reported in the previous request is just the outcome from my command line (Mac OS terminal), and the code I run in the python file 'networkx-test.py' it is copied as-it-is from your 'Quick Example:' on your GitHub at URL:

https://github.com/VHRanger/nodevectors

Hope this clarifies better the previous post, thank you again. 

BR
Hyrundo

**Comment by VHRanger** [comment]
Thanks, the docs are fixed now.

They're quirks  (having .zip or not in the method arguments) with the hand-rolled serialization module I wrote a while ago. They come from python's `zipfile` standard library having these quirks. 

Feel free to open an issue relating to these, but I'll close this one for now.

Thanks for the compliments on the code and enjoying my blog!
