### ISSUE TITLE
Tuning model

### ISSUE THREAD

**Issue by MrPaulAlbert** [VHRanger/nodevectors#24]
Is there a way to pass parameters (e.g., epoch=100) in the command line?

For example:
g2v = Node2Vec()
g2v.fit(GCC, walklen=30, epochs=100 )

Thanks!

**Comment by VHRanger** [comment]
parameters are passed in the model, not the fit method, like in the sklearn API.

g2v = Node2Vec(walklen=30, epochs=100 )
g2v.fit(GCC)
________________________________
