### ISSUE TITLE
Could not broadcast input array

### ISSUE THREAD

**Issue by vndeeatteekee** [VHRanger/nodevectors#26]
Hi **VHRanger**,
Thanks for your great works. I am trying to run node2vec with around 4 million nodes and more than 48 million edges. But I got this issue. Can you give me some advice to deal with this big graph?

```
sys:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
Traceback (most recent call last):
  File "node2vec/graph_builder/csr.py", line 26, in <module>
    gr = CSRGraphNode2Vec()
  File "node2vec/graph_builder/csr.py", line 9, in __init__
    self.graph = cg.read_edgelist(file_path, directed=False, sep=',')
  File "/data/quocpbc/anaconda3/lib/python3.8/site-packages/csrgraph/graph.py", line 523, in read_edgelist
    G = methods._edgelist_to_graph(
  File "/data/quocpbc/anaconda3/lib/python3.8/site-packages/csrgraph/methods.py", line 31, in _edgelist_to_graph
    new_src[1:] = np.cumsum(np.bincount(src, minlength=nnodes))
ValueError: could not broadcast input array from shape (2147483649) into shape (4790294)
```

**Comment by VHRanger** [comment]
So the value on the left hand side or your error (2147483649) is (2**31) or INT32_MAX. This is normally indicative that we've overrun some int32 value.

Would it be possible to send me the file you're trying to load through a Google Drive/OneDrive/Dropbox link? 

It's definitely a bug in my csrgraphs package, but I'm not sure what's causing the edge source array passed to np.bincount to have a max value greater than INT32_MAX

**Comment by VHRanger** [comment]
Also note the pandas read_csv warning when you load the graph. This might help: 

https://stackoverflow.com/questions/24251219/pandas-read-csv-low-memory-and-dtype-options

**Comment by VHRanger** [comment]
Since this isn't being expanded upon, and I can't replicate it, I'll close the issue.

Please message me or reopen an issue if you run into anything, or this persists
