### ISSUE TITLE
numba dependency is not pinned; latest version of numba breaks nodevectors

### ISSUE THREAD

**Issue by herbiehuff** [VHRanger/nodevectors#33]
Recently numba removed jitclass from it's module `__init__`. This breaks the import of jitclass.
https://github.com/numba/numba/commit/4976953d9cdab87c82533c653dc463cf319f227c

Nodevectors imports jitclass so the dependency needs to be pinned.

Pinning to 0.51.2 fixes the import of nodevectors.

**Comment by VHRanger** [comment]
We don't use jitclass anymore so I can remove it entirely.

It was tried to map random walks to node names faster but was a pain.

**Comment by VHRanger** [comment]
This was actually fixed in a previous release of `csrgraph`.

Please run `pip install --upgrade csrgraph` to fix it.
