### ISSUE TITLE
is it possible to split n2v to generate walks only?

### ISSUE THREAD

**Issue by amjass12** [VHRanger/nodevectors#39]
Hi! , 

I am using node2vec to generate walks on graphs which i then pass to a different gensim modified by another tool (ths is for alignment of temporal models) - 

Given the speed of carrying out walks with nodevectors - is it possible to separate the walks from the .fit method (as in have an option to ONLY carry out the walks without fitting the model so that i can just then save the walks to take on to the next tool?

thanks!

**Comment by VHRanger** [comment]
Yeah, specify `n2v = Node2Vec(keep_walks=True)` in the node2vec object, then you have access to them in the object after fitting with `n2v.walks`

**Comment by amjass12** [comment]
Thank you, and is there a way if generating the walk without fitting the model? This would speed up the process even more, is there an easy way to do this?

**Comment by VHRanger** [comment]
You can do it from the CSRGraph object directly, but that returns the node IDs rather than the node names (even if node names are integers, the IDs aren't necessarily the same).  So you'd have to map it back, here's a sketch of how to do it, taken from the `Node2Vec` fit method:


```python
import csrgraph as cg
G =  cg.csrgraph(INPUT_DATA)
walks = G.random_walks()
# Make into dataframe to map ID to names
walks = pd.DataFrame(walks)
# mapping dict node ID -> node name
node_dict = dict(zip(np.arange(len(G.names)), G.names))
for col in walks.columns:
      walks[col] = walks[col].map(node_dict).astype(str)
```

**Comment by amjass12** [comment]
Thank you! This is a good workaround. Appreciate your time
