### ISSUE TITLE
Why is generating walks so slow with non-default parameters?

### ISSUE THREAD

**Issue by ldorigo** [VHRanger/nodevectors#48]
I initially arrived at this code via your blog post https://www.singlelunch.com/2019/08/01/700x-faster-node2vec-models-fastest-random-walks-on-a-graph/#note-3-692 - and indeed the speedup with default parameters (q=1,p=1) is impressive.

But as you also mention in the readme, much of that is lost when using non-default parameters. I have a network of 100k nodes and 1M edges, and the "default" walk generation takes 14 seconds, while trying different parameters takes well over 10 hours. Is there anything that can be done to improve speed for different values of p and q? much of the flexibility of Node2Vec comes form being able to capture local vs. global information by tuning the parameters, and even the Node2Vec paper shows that the best results are usually obtained with values for p and q that are different from 1.

**Comment by VHRanger** [comment]
It's a question of just the amount of work and how efficiently it can be done - you need to resample at each step of each random walk in Node2Vec walks and this also breaks cache locality.

Theres been some research done in making it faster through rejection sampling: https://louisabraham.github.io/articles/node2vec-sampling.html

Which weve been looking into merging into CSRGraphs: https://github.com/VHRanger/CSRGraph/pull/14

That said, as noted in the README, I encourage you to try other algorithms (ProNE, GGVec) before spending a lot of resources gridsearching p and q on Node2Vec. As mentionned in [this blog post](https://www.singlelunch.com/2020/12/28/why-im-lukewarm-on-graph-neural-networks/), you need to gridsearch p & q a lot on Node2Vec for it to show a difference and this is time better spent gridsearching other parameters with more efficient methods.

**Comment by ldorigo** [comment]
> That said, as noted in the README, I encourage you to try other algorithms (ProNE, GGVec) before spending a lot of resources gridsearching p and q on Node2Vec. As mentionned in this blog post, you need to gridsearch p & q a lot on Node2Vec for it to show a difference and this is time better spent gridsearching other parameters (the w2vparams for instance) with more efficient methods.

Just read it, great article. Although at this point I'm mostly stuck with Node2Vec because I would have to rewrite a major part of my thesis to use another algorithm.

FYI, since writing here I've tried using Node2Vec's actual reference implementation in C++ (https://github.com/snap-stanford/snap/tree/master/examples/node2vec), and the walks are ridiculously fast to generate (a few seconds for my network for any combination of parameters). I don't think any of the python implementations leverage the markov property the way they describe in the paper (i.e. that you can generate partial walks for many nodes at once because the next node only depends on the current node and the previous one). Anyhow, thanks for answering - feel free to close this issue, I'm now using the c++ implementation so my problem is solved :-)

**Comment by VHRanger** [comment]
Thanks, since it's tracked in the rejective sampling issue we'll track progress on faster (p or q) != 1 walks there
