### ISSUE TITLE
word2vec parameters changed

### ISSUE THREAD

**Issue by daniel-unyi-42** [VHRanger/nodevectors#49]
Hi!

In node2vec.py, you should modify the 'iter' parameter to 'epochs' and the 'size' parameter to 'vector_size'.

(And thank you for the library, I use it extensively in my research!)

**Comment by VHRanger** [comment]
The parameters in the `Node2Vec` class are to stay consistent with SKLearn conventions (`n_components` and `epochs`)

Do you mean the ones passed  to gensim are erroneous?

**Comment by daniel-unyi-42** [comment]
Yes, the parameter names in the constructor of _gensim.models.Word2Vec_ were changed.
Sorry for the misunderstanding.

**Comment by VHRanger** [comment]
Ah, actually it's tracked here:

https://github.com/VHRanger/nodevectors/issues/37

I'll close this one and resolve the other one right away
