### ISSUE TITLE
ProNE multithread

### ISSUE THREAD

**Issue by ashkspark** [VHRanger/nodevectors#55]
Just want to know if ProNE is multithreaded? Is there a way to control the number of threads like the implemented Node2Vec?

**Comment by VHRanger** [comment]
Hey,

The ProNE algorithm is inherently sequential. Right now it mainly leverages scipy and numpy:

https://github.com/VHRanger/nodevectors/blob/master/nodevectors/prone.py#L155

Some parts could be optimized (the sparse matrix multiplications could be rewritten in optimized numba or C++) which could leverage a little bit of parallelism, but nothing like the node2vec which is an inherently parallel algorithm (generating random walks in embarassingly parallel)
