### ISSUE TITLE
Rename repo/package

### ISSUE THREAD

**Issue by cthoyt** [VHRanger/nodevectors#7]
Unfortunately, `graph2vec` has already been used in 2017 in a paper on representation learning for whole graphs (not nodes). Link: https://arxiv.org/abs/1707.05005, implementations at https://github.com/MLDroid/graph2vec_tf (author) and https://github.com/benedekrozemberczki/graph2vec (reimplementation)

Also, graph2vec has already been taken on PyPI by another project https://pypi.org/project/graph2vec, but I think you're aware of this.

I think the solution was to rename this to graph2vec-learn but I would encourage you pick a more informative name because this doesn't alleviate the original name conflict.

Either way, could you please update the name of this repo so the PyPI project matches the repo and folder inside the repo?

**Comment by cthoyt** [comment]
Thanks @VHRanger. Really happy to have this implementation - it's wonderful!

**Comment by VHRanger** [comment]
Sorry about the delay!

I should be quicker on maintenance now, since this got broken up into packages, and is going to be used for forthcoming blogposts and perhaps a paper on my end, so I'm actively developing it again.
